---
title: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br><br>
Détection d’anomalies dans les coefficients de réduction-majoration (CRM) ou bonus-malus renseignés à la souscription d’un contrat automobile. Le jeu de données sera fourni par Allianz.<br><br>

Un coefficient bonus-malus, c’est-à-dire ?<br><br>

Lors de la souscription d’un contrat automobile, l’assureur doit déterminer la prime annuelle de son assuré en fonction de certaines caractéristiques (âge et modèle de la voiture, …).  La compagnie d’assurance a donc intérêt à utiliser le plus d’informations possible sur ses assurés pour identifier les risques faibles (« bons » conducteurs) des risques élevés (« mauvais » conducteurs). Afin de déterminer au mieux la prime de chaque assuré, le système Bonus-Malus est utilisé.  Celui-ci consiste à multiplier la prime par un coefficient (compris entre 0.5 et 3.5), variable selon la survenance d’un ou plusieurs sinistres dans l’année précédente.<br>
Il arrive que les assurés déclarent un coefficient de Bonus-Malus erroné.<br><br>
 
Le but sera donc de détecter ces anomalies par le biais d’une analyse algorithmique du jeu de donnée :<br>
<ul>
  <li>règles déterministes (et les écarts)</li>
  <li>apprentissage non supervisé</li>
  <li>apprentissage supervisé</li>
</ul>


<br>
Règles de calcul du CRM:<br> http://www.kelassur.com/assurance-auto/article/guide/calcul-du-bonus-malus-avec-le-crm
<br><br>
Contenu à ne pas diffuser<br>

Résultats<br>
<ul>
  <li>les étudiants doivent détecter des contrats anormaux où le coefficient de bonus malus présente un écart important par rapport à la prédiction. Pour chaque contrat détecté, les critères peuvent être différents. Ainsi, il est nécessaire d’expliquer clairement pour quelles raisons les contrats sont considérés comme anormaux.</li>
  <li>Ensuite une vision par intermédiaire doit être construite. C’est une synthèse claire des contrats anormaux détectés.</li>

</ul>
<br>
Résultat benchmark<br>
<ul>
  <li>on peut calculer la moyenne des CRM par intermédiaire. On classe les intermédiaires par ordre croissant. Ceux qui ont une moyenne inférieure notablement à la moyenne nationale seront contrôlés en priorité.</li>
  <li>Maintenant pour contrats à à contrôler, on va prendre ceux qui ont le plus faible CRM, c’est-à-dire 0.50.</li>
  </ul>



Amélioration du benchmark: quelques idées très simples pour améliorer:<br>
on peut appliquer la règle de calcul du CRM, et étudier les écarts entre le minimum théorique, et celui qui est saisi. Ainsi, on peut classer les intermédiaires selon l’ordre croissant de la moyenne des écarts.<br>
Ensuite, on peut sélectionner les contrats qui ont des écarts, voire négatifs.

Modèle d’apprentissage supervisé<br>
Classification : on peut travailler dans un premier temps sur les CRM 0.50. Le modèle de classification consiste à créer un modèle qui prédit le CRM.<br>
Régression: créer un modèle qui permet de prédire le CRM de façon continue
On peut ensuite agréger par intermédiaire, ainsi on saura qui a des écarts importants<br><br>

Modèle d’apprentissage non-supervisé<br>
Détecter les cas atypiques, en terme de CRM<br>
Vous pouvez travailler sur des anomalies de façon générale, sans forcément d’anomalie sur le CRM, par exemple, un jeune de 26 ans qui a une ferrari, c’est atypique.<br><br>

